logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    fr.codecake.ecom: INFO

spring:
  application:
    name: Ecommerce Backend
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        default_schema: ecommerce_yt
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.xml
    default-schema: ecommerce_yt
    contexts: dev
  #    drop-first: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://codecake.kinde.com
          jwk-set-uri: https://codecake.kinde.com/.well-known/jwks
          audiences: http://localhost:8080/api
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

application:
  client-base-url: http://localhost:4200
  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: false
    max-age: 300
  kinde:
    api: https://codecake.kinde.com
    client-id: ${KINDE_CLIENT_ID}
    client-secret: ${KINDE_CLIENT_SECRET}
    audience: https://codecake.kinde.com/api
  stripe:
    api-key: ${STRIPE_API_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}
